import os

from taipan.pathes import TABLES_DIR
from taipan.generictable import GenericTable
from taipan.mapper.properties.connectivity import map_table_properties_connectivity, \
    get_all_dict_values, group_properties_by_column

TEST_FILENAME = os.path.join(TABLES_DIR, "cardinals_table.csv")

def test_map_atomic_table_property():
    table = GenericTable(TEST_FILENAME)
    table.init()
    _property = map_table_properties_connectivity(table)
    assert _property == "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"

def test_get_all_dict_values():
    _dict = {0:
             {
                 0: [],
                 1: [
                     'http://purl.org/dc/terms/description',
                     'http://dbpedia.org/ontology/wikiPageWikiLink',
                     'http://dbpedia.org/ontology/abstract',
                     'http://www.w3.org/1999/02/22-rdf-syntax-ns#type',
                     'http://www.w3.org/2000/01/rdf-schema#comment',
                     'http://dbpedia.org/property/title',
                     'http://purl.org/dc/terms/subject']},
             1: {0: [
                 'http://purl.org/dc/terms/description',
                 'http://dbpedia.org/ontology/wikiPageWikiLink',
                 'http://dbpedia.org/ontology/abstract',
                 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type',
                 'http://www.w3.org/2000/01/rdf-schema#comment',
                 'http://dbpedia.org/property/title',
                 'http://purl.org/dc/terms/subject'],
                 1: []}}
    result = []
    values = get_all_dict_values(_dict, result)
    assert len(values) == 14

PROPERTY_RESULT = [{0: {0: [], 1: ['http://dbpedia.org/ontology/wikiPageWikiLink']}, 1: {0: ['http://dbpedia.org/ontology/wikiPageWikiLink'], 1: []}},
 {0: {0: [], 1: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type']}, 1: {0: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type'], 1: []}},
 {0: {0: [], 1: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type']}, 1: {0: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type'], 1: []}},
 {0: {0: [], 1: []}, 1: {0: [], 1: []}},
 {0: {0: [], 1: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type']}, 1: {0: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type'], 1: []}},
 {0: {0: [],
      1: ['http://purl.org/dc/terms/description',
          'http://dbpedia.org/ontology/wikiPageWikiLink',
          'http://dbpedia.org/ontology/wikiPageRedirects',
          'http://purl.org/dc/terms/subject',
          'http://www.w3.org/2000/01/rdf-schema#comment',
          'http://dbpedia.org/ontology/abstract',
          'http://www.w3.org/1999/02/22-rdf-syntax-ns#type']},
  1: {0: ['http://purl.org/dc/terms/description',
          'http://dbpedia.org/ontology/wikiPageWikiLink',
          'http://dbpedia.org/ontology/wikiPageRedirects',
          'http://purl.org/dc/terms/subject',
          'http://www.w3.org/2000/01/rdf-schema#comment',
          'http://dbpedia.org/ontology/abstract',
          'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'],
      1: []}},
 {0: {0: [],
      1: ['http://purl.org/dc/terms/description',
          'http://dbpedia.org/property/relstyle',
          'http://dbpedia.org/ontology/wikiPageWikiLink',
          'http://dbpedia.org/ontology/wikiPageRedirects',
          'http://purl.org/dc/terms/subject',
          'http://www.w3.org/2000/01/rdf-schema#comment',
          'http://dbpedia.org/ontology/abstract',
          'http://dbpedia.org/property/title',
          'http://www.w3.org/1999/02/22-rdf-syntax-ns#type']},
  1: {0: ['http://purl.org/dc/terms/description',
          'http://dbpedia.org/property/relstyle',
          'http://dbpedia.org/ontology/wikiPageWikiLink',
          'http://dbpedia.org/ontology/wikiPageRedirects',
          'http://purl.org/dc/terms/subject',
          'http://www.w3.org/2000/01/rdf-schema#comment',
          'http://dbpedia.org/ontology/abstract',
          'http://dbpedia.org/property/title',
          'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'],
      1: []}},
 {0: {0: [], 1: []}, 1: {0: [], 1: []}},
 {0: {0: [], 1: []}, 1: {0: [], 1: []}},
 {0: {0: [], 1: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type']}, 1: {0: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type'], 1: []}},
 {0: {0: [],
      1: ['http://purl.org/dc/terms/description',
          'http://dbpedia.org/ontology/wikiPageWikiLink',
          'http://dbpedia.org/ontology/wikiPageRedirects',
          'http://purl.org/dc/terms/subject',
          'http://www.w3.org/2000/01/rdf-schema#comment',
          'http://dbpedia.org/ontology/abstract',
          'http://www.w3.org/1999/02/22-rdf-syntax-ns#type']},
  1: {0: ['http://purl.org/dc/terms/description',
          'http://dbpedia.org/ontology/wikiPageWikiLink',
          'http://dbpedia.org/ontology/wikiPageRedirects',
          'http://purl.org/dc/terms/subject',
          'http://www.w3.org/2000/01/rdf-schema#comment',
          'http://dbpedia.org/ontology/abstract',
          'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'],
      1: []}},
 {0: {0: [], 1: []}, 1: {0: [], 1: []}},
 {0: {0: [], 1: ['http://dbpedia.org/ontology/wikiPageWikiLink', 'http://purl.org/dc/terms/subject', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type']},
  1: {0: ['http://dbpedia.org/ontology/wikiPageWikiLink', 'http://purl.org/dc/terms/subject', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'], 1: []}},
 {0: {0: [], 1: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type']}, 1: {0: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type'], 1: []}},
 {0: {0: [], 1: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type']}, 1: {0: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type'], 1: []}},
 {0: {0: [], 1: []}, 1: {0: [], 1: []}},
 {0: {0: [], 1: []}, 1: {0: [], 1: []}},
 {0: {0: [], 1: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type']}, 1: {0: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type'], 1: []}},
 {0: {0: [],
      1: ['http://purl.org/dc/terms/description',
          'http://dbpedia.org/ontology/wikiPageWikiLink',
          'http://dbpedia.org/ontology/wikiPageRedirects',
          'http://purl.org/dc/terms/subject',
          'http://www.w3.org/2000/01/rdf-schema#comment',
          'http://xmlns.com/foaf/0.1/depiction',
          'http://dbpedia.org/ontology/thumbnail',
          'http://dbpedia.org/ontology/abstract',
          'http://www.w3.org/1999/02/22-rdf-syntax-ns#type']},
  1: {0: ['http://purl.org/dc/terms/description',
          'http://dbpedia.org/ontology/wikiPageWikiLink',
          'http://dbpedia.org/ontology/wikiPageRedirects',
          'http://purl.org/dc/terms/subject',
          'http://www.w3.org/2000/01/rdf-schema#comment',
          'http://xmlns.com/foaf/0.1/depiction',
          'http://dbpedia.org/ontology/thumbnail',
          'http://dbpedia.org/ontology/abstract',
          'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'],
      1: []}},
 {0: {0: [],
      1: ['http://dbpedia.org/ontology/wikiPageWikiLink',
          'http://purl.org/dc/terms/subject',
          'http://www.w3.org/2000/01/rdf-schema#comment',
          'http://dbpedia.org/ontology/abstract',
          'http://dbpedia.org/property/title',
          'http://www.w3.org/1999/02/22-rdf-syntax-ns#type']},
  1: {0: ['http://dbpedia.org/ontology/wikiPageWikiLink',
          'http://purl.org/dc/terms/subject',
          'http://www.w3.org/2000/01/rdf-schema#comment',
          'http://dbpedia.org/ontology/abstract',
          'http://dbpedia.org/property/title',
          'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'],
      1: []}},
 {0: {0: [], 1: []}, 1: {0: [], 1: []}},
 {0: {0: [], 1: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type']}, 1: {0: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type'], 1: []}},
 {0: {0: [], 1: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type']}, 1: {0: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type'], 1: []}},
 {0: {0: [], 1: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type']}, 1: {0: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type'], 1: []}},
 {0: {0: [],
      1: ['http://purl.org/dc/terms/description',
          'http://dbpedia.org/ontology/wikiPageWikiLink',
          'http://dbpedia.org/ontology/wikiPageRedirects',
          'http://purl.org/dc/terms/subject',
          'http://www.w3.org/2000/01/rdf-schema#comment',
          'http://dbpedia.org/ontology/abstract',
          'http://dbpedia.org/property/title',
          'http://www.w3.org/1999/02/22-rdf-syntax-ns#type']},
  1: {0: ['http://purl.org/dc/terms/description',
          'http://dbpedia.org/ontology/wikiPageWikiLink',
          'http://dbpedia.org/ontology/wikiPageRedirects',
          'http://purl.org/dc/terms/subject',
          'http://www.w3.org/2000/01/rdf-schema#comment',
          'http://dbpedia.org/ontology/abstract',
          'http://dbpedia.org/property/title',
          'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'],
      1: []}},
 {0: {0: [], 1: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type']}, 1: {0: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type'], 1: []}},
 {0: {0: [], 1: ['http://dbpedia.org/ontology/abstract', 'http://www.w3.org/2000/01/rdf-schema#comment', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type']},
  1: {0: ['http://dbpedia.org/ontology/abstract', 'http://www.w3.org/2000/01/rdf-schema#comment', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'], 1: []}},
 {0: {0: [],
      1: ['http://purl.org/dc/terms/description',
          'http://dbpedia.org/property/rank',
          'http://dbpedia.org/ontology/wikiPageWikiLink',
          'http://dbpedia.org/ontology/wikiPageRedirects',
          'http://purl.org/dc/terms/subject',
          'http://www.w3.org/2000/01/rdf-schema#comment',
          'http://dbpedia.org/ontology/abstract',
          'http://dbpedia.org/property/type',
          'http://dbpedia.org/property/title',
          'http://dbpedia.org/property/otherPost',
          'http://www.w3.org/1999/02/22-rdf-syntax-ns#type']},
  1: {0: ['http://purl.org/dc/terms/description',
          'http://dbpedia.org/property/rank',
          'http://dbpedia.org/ontology/wikiPageWikiLink',
          'http://dbpedia.org/ontology/wikiPageRedirects',
          'http://purl.org/dc/terms/subject',
          'http://www.w3.org/2000/01/rdf-schema#comment',
          'http://dbpedia.org/ontology/abstract',
          'http://dbpedia.org/property/type',
          'http://dbpedia.org/property/title',
          'http://dbpedia.org/property/otherPost',
          'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'],
      1: []}},
 {0: {0: [], 1: []}, 1: {0: [], 1: []}},
 {0: {0: [], 1: []}, 1: {0: [], 1: []}},
 {0: {0: [], 1: []}, 1: {0: [], 1: []}},
 {0: {0: [], 1: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type']}, 1: {0: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type'], 1: []}},
 {0: {0: [], 1: []}, 1: {0: [], 1: []}},
 {0: {0: [],
      1: ['http://dbpedia.org/ontology/wikiPageWikiLink', 'http://purl.org/dc/terms/description', 'http://dbpedia.org/ontology/wikiPageExternalLink', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type']},
  1: {0: ['http://dbpedia.org/ontology/wikiPageWikiLink', 'http://purl.org/dc/terms/description', 'http://dbpedia.org/ontology/wikiPageExternalLink', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'],
      1: []}},
 {0: {0: [], 1: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type']}, 1: {0: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type'], 1: []}},
 {0: {0: [], 1: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type']}, 1: {0: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type'], 1: []}},
 {0: {0: [], 1: []}, 1: {0: [], 1: []}},
 {0: {0: [],
      1: ['http://www.w3.org/2000/01/rdf-schema#label',
          'http://purl.org/dc/terms/description',
          'http://dbpedia.org/ontology/wikiPageWikiLink',
          'http://purl.org/dc/terms/subject',
          'http://www.w3.org/2000/01/rdf-schema#comment',
          'http://www.w3.org/2002/07/owl#sameAs',
          'http://dbpedia.org/property/caption',
          'http://dbpedia.org/ontology/abstract',
          'http://dbpedia.org/property/type',
          'http://www.w3.org/1999/02/22-rdf-syntax-ns#type']},
  1: {0: ['http://www.w3.org/2000/01/rdf-schema#label',
          'http://purl.org/dc/terms/description',
          'http://dbpedia.org/ontology/wikiPageWikiLink',
          'http://purl.org/dc/terms/subject',
          'http://www.w3.org/2000/01/rdf-schema#comment',
          'http://www.w3.org/2002/07/owl#sameAs',
          'http://dbpedia.org/property/caption',
          'http://dbpedia.org/ontology/abstract',
          'http://dbpedia.org/property/type',
          'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'],
      1: []}},
 {0: {0: [],
      1: ['http://purl.org/dc/terms/description',
          'http://dbpedia.org/property/successor',
          'http://dbpedia.org/ontology/wikiPageWikiLink',
          'http://dbpedia.org/property/consecratedBy',
          'http://purl.org/dc/terms/subject',
          'http://www.w3.org/2000/01/rdf-schema#comment',
          'http://dbpedia.org/property/predecessor',
          'http://dbpedia.org/ontology/abstract',
          'http://dbpedia.org/property/title',
          'http://dbpedia.org/property/otherPost',
          'http://www.w3.org/1999/02/22-rdf-syntax-ns#type']},
  1: {0: ['http://purl.org/dc/terms/description',
          'http://dbpedia.org/property/successor',
          'http://dbpedia.org/ontology/wikiPageWikiLink',
          'http://dbpedia.org/property/consecratedBy',
          'http://purl.org/dc/terms/subject',
          'http://www.w3.org/2000/01/rdf-schema#comment',
          'http://dbpedia.org/property/predecessor',
          'http://dbpedia.org/ontology/abstract',
          'http://dbpedia.org/property/title',
          'http://dbpedia.org/property/otherPost',
          'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'],
      1: []}},
 {0: {0: [],
      1: ['http://purl.org/dc/terms/description',
          'http://dbpedia.org/ontology/wikiPageWikiLink',
          'http://dbpedia.org/ontology/wikiPageRedirects',
          'http://purl.org/dc/terms/subject',
          'http://www.w3.org/2000/01/rdf-schema#comment',
          'http://dbpedia.org/ontology/abstract',
          'http://dbpedia.org/property/title',
          'http://www.w3.org/1999/02/22-rdf-syntax-ns#type']},
  1: {0: ['http://purl.org/dc/terms/description',
          'http://dbpedia.org/ontology/wikiPageWikiLink',
          'http://dbpedia.org/ontology/wikiPageRedirects',
          'http://purl.org/dc/terms/subject',
          'http://www.w3.org/2000/01/rdf-schema#comment',
          'http://dbpedia.org/ontology/abstract',
          'http://dbpedia.org/property/title',
          'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'],
      1: []}},
 {0: {0: [],
      1: ['http://dbpedia.org/ontology/wikiPageWikiLink',
          'http://dbpedia.org/ontology/abstract',
          'http://dbpedia.org/property/previousPost',
          'http://www.w3.org/2000/01/rdf-schema#comment',
          'http://www.w3.org/1999/02/22-rdf-syntax-ns#type']},
  1: {0: ['http://dbpedia.org/ontology/wikiPageWikiLink',
          'http://dbpedia.org/ontology/abstract',
          'http://dbpedia.org/property/previousPost',
          'http://www.w3.org/2000/01/rdf-schema#comment',
          'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'],
      1: []}},
 {0: {0: [], 1: []}, 1: {0: [], 1: []}},
 {0: {0: [], 1: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type']}, 1: {0: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type'], 1: []}},
 {0: {0: [], 1: []}, 1: {0: [], 1: []}},
 {0: {0: [], 1: []}, 1: {0: [], 1: []}},
 {0: {0: [], 1: []}, 1: {0: [], 1: []}},
 {0: {0: [], 1: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type']}, 1: {0: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type'], 1: []}},
 {0: {0: [],
      1: ['http://purl.org/dc/terms/description',
          'http://dbpedia.org/ontology/wikiPageWikiLink',
          'http://purl.org/dc/terms/subject',
          'http://www.w3.org/2000/01/rdf-schema#comment',
          'http://dbpedia.org/property/as',
          'http://dbpedia.org/ontology/abstract',
          'http://dbpedia.org/property/title',
          'http://www.w3.org/1999/02/22-rdf-syntax-ns#type']},
  1: {0: ['http://purl.org/dc/terms/description',
          'http://dbpedia.org/ontology/wikiPageWikiLink',
          'http://purl.org/dc/terms/subject',
          'http://www.w3.org/2000/01/rdf-schema#comment',
          'http://dbpedia.org/property/as',
          'http://dbpedia.org/ontology/abstract',
          'http://dbpedia.org/property/title',
          'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'],
      1: []}},
 {0: {0: [],
      1: ['http://purl.org/dc/terms/description',
          'http://dbpedia.org/ontology/wikiPageWikiLink',
          'http://purl.org/dc/terms/subject',
          'http://www.w3.org/2000/01/rdf-schema#comment',
          'http://dbpedia.org/ontology/abstract',
          'http://dbpedia.org/property/type',
          'http://dbpedia.org/property/title',
          'http://www.w3.org/1999/02/22-rdf-syntax-ns#type']},
  1: {0: ['http://purl.org/dc/terms/description',
          'http://dbpedia.org/ontology/wikiPageWikiLink',
          'http://purl.org/dc/terms/subject',
          'http://www.w3.org/2000/01/rdf-schema#comment',
          'http://dbpedia.org/ontology/abstract',
          'http://dbpedia.org/property/type',
          'http://dbpedia.org/property/title',
          'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'],
      1: []}},
 {0: {0: [],
      1: ['http://purl.org/dc/terms/description',
          'http://dbpedia.org/ontology/wikiPageWikiLink',
          'http://purl.org/dc/terms/subject',
          'http://www.w3.org/2000/01/rdf-schema#comment',
          'http://dbpedia.org/ontology/abstract',
          'http://www.w3.org/1999/02/22-rdf-syntax-ns#type']},
  1: {0: ['http://purl.org/dc/terms/description',
          'http://dbpedia.org/ontology/wikiPageWikiLink',
          'http://purl.org/dc/terms/subject',
          'http://www.w3.org/2000/01/rdf-schema#comment',
          'http://dbpedia.org/ontology/abstract',
          'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'],
      1: []}},
 {0: {0: [], 1: []}, 1: {0: [], 1: []}},
 {0: {0: [], 1: []}, 1: {0: [], 1: []}},
 {0: {0: [], 1: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type']}, 1: {0: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type'], 1: []}},
 {0: {0: [], 1: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type']}, 1: {0: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type'], 1: []}},
 {0: {0: [], 1: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type']}, 1: {0: ['http://www.w3.org/1999/02/22-rdf-syntax-ns#type'], 1: []}},
 {0: {0: [], 1: []}, 1: {0: [], 1: []}}]


def test_map_properties_to_columns():
    result = group_properties_by_column(PROPERTY_RESULT)
    import ipdb; ipdb.set_trace()
